### PR TITLE
SW-3510 adding a quicktext starting with will crash the slicing

### PR DESCRIPTION
**Pull request by hungerpirat**
changed two regexes:
1st one to filter . chars
2nd one to hop in fallback naming mode earlier. formerly only last character was checked.

### CODE REVIEW

**Comment by Josef-MrBeam** [comment]
Please change the target branch to stable

**Review by JFSolution — CHANGES_REQUESTED** [review]
please change target branch to stable

**Comment by hungerpirat** [comment]
@Josef-MrBeam now merging into stable...

**Review by JFSolution — APPROVED** [review]

**Comment by JFSolution** [comment]
Please make sure to squash and merge and set a commit message including the ticket number

**Pull request merged**
