### PR TITLE
SW-742-mrbeam-plugin-init-failed-after-update-to-alpha-0-10-0

### PR DESCRIPTION
**Pull request by ahmed-mrbeam**
Please refer to the issue for more details
https://mr-beam.atlassian.net/browse/SW-742

### CODE REVIEW

**Review by amrsoll — COMMENTED** [review]
I think we are mixing up stuff by renaming this the wrong thing (as lh_model and lh_model_id are different)

**Comment by ahmed-mrbeam** [comment]
> I think we are mixing up stuff by renaming this the wrong thing (as lh_model and lh_model_id are different)

@amrsoll explain more

**Comment by amrsoll** [comment]
I understand better. The screenshots fo the text were confusing. What you are looking to use is the lh_model_string perhaps, and you would have to do the reverse mapping to get the ID back

**Review by Yelko-mrbeam — APPROVED** [review]

**Comment by amrsoll** [comment]
I think your fix will break because the values are different

**Comment by amrsoll** [comment]
or perhaps there is a migration step, in which case going back to beta from alpha might break

**Review by amrsoll — APPROVED** [review]

**Comment by amrsoll** [comment]
For context,. the matter was discussed offline: The key was preserved from previous version to prevent using one more migration step ; and the values get sanitised at an other location in the code.

**Pull request merged**
