### PR TITLE
SW-1090 add native lazy loading of images

### PR DESCRIPTION
**Pull request by Yelko-mrbeam**
https://mr-beam.atlassian.net/browse/SW-1090

### CODE REVIEW

**Comment by ahmed-mrbeam** [comment]
Do we need to explicitly mention it for each and every image ?

**Comment by Yelko-mrbeam** [comment]
> Do we need to explicitly mention it for each and every image ?

I wanted to keep the solution as simple as possible, so without JS. Unfortunately I didn't find anything that would apply as a general rule on the html...

**Review by irlaec — APPROVED** [review]

**Comment by irlaec** [comment]
@Yelko-mrbeam Please change the name of the PR to include the issue id SW-1090

**Comment by Yelko-mrbeam** [comment]
> @Yelko-mrbeam Please change the name of the PR to include the issue id SW-1090

done 😄

**Comment by Yelko-mrbeam** [comment]
I also moved the PR to be to alpha @irlaec and now there are conflicts... 😢

**Comment by Yelko-mrbeam** [comment]
I'll close this one since I created a new one https://github.com/mrbeam/MrBeamPlugin/pull/1562

**Pull request closed without merging**
